Repository ormcamp-fe-3rd/Orm-Tour, pull requests merged in 2024-11, with the labels that each got.

#23 [조지연] Conf - 레이아웃 추가, 예약 조회 기능 구현
  confirmation-page/css/.css
  confirmation-page/css/confirm.css
  confirmation-page/html/.html
  confirmation-page/html/confirm.html
  confirmation-page/src/.js
  confirmation-page/src/reservation-cancel.js
  confirmation-page/src/reservation-search.js
Labels: Step1, Step2

#30 로고 이미지 변경
  banner/css/banner.css
  banner/html/banner.html
  banner/src/banner.js
  banner/src/images/0001.mov
  banner/src/images/0003.webm
  banner/src/images/0003.webm.xmp
  banner/src/images/Group2.png
  main-page/css/main-page.css
  main-page/html/main-page.html
  main-page/src/images/0001.mov
  main-page/src/images/0003.webm
  main-page/src/images/0003.webm.xmp
  main-page/src/images/Group2.png
  main-page/src/images/logo.png
  main-page/src/images/ormlogo.png
  main-page/src/main-page.js
  product-page/css/.css
  product-page/css/product-page.css
  product-page/html/.html
  product-page/html/product-page.html
  product-page/src/.js
  product-page/src/product-page.js
Labels: HTML, CSS

#32 [조지연] confirmation-page 1차 마감본 병합
  confirmation-page/css/confirm.css
  confirmation-page/html/confirm.html
  confirmation-page/src/reservation-search.js
  main-page/css/.css
  main-page/css/main-page.css
  main-page/html/.html
  main-page/html/main-page.html
  main-page/src/.js
Labels: 기능 향상

#34 [손동진] Reservation page total
  README.md
  reservation-page/css/response.css
  reservation-page/css/section.css
  reservation-page/html/example.html
  reservation-page/html/section01.html
  reservation-page/img/10.jpg
  reservation-page/img/2.jpg
  reservation-page/img/3.jpg
  reservation-page/img/4.jpg
  reservation-page/img/5.jpg
  reservation-page/img/6.jpg
  reservation-page/img/7.jpg
  reservation-page/img/8.jpg
  reservation-page/img/9.jpg
  reservation-page/img/Group.svg
  reservation-page/img/Vector-1.svg
  reservation-page/img/Vector.svg
  reservation-page/img/autum.jpg
  reservation-page/img/autum1.jpg
  reservation-page/img/autum2.jpg
  reservation-page/img/autum3.jpg
  reservation-page/img/user.jpg
  reservation-page/src/modal.js
  reservation-page/src/page.js
Labels: 기능 향상, HTML, JS, CSS

#37 [손동진] 버그 수정하기
  reservation-page/html/section01.html
  reservation-page/src/page.js
  reservation-page[최종본]/css/response.css
  reservation-page[최종본]/css/section.css
  reservation-page[최종본]/html/example.html
  reservation-page[최종본]/html/section01.html
  reservation-page[최종본]/img/10.jpg
  reservation-page[최종본]/img/2.jpg
  reservation-page[최종본]/img/3.jpg
  reservation-page[최종본]/img/4.jpg
  reservation-page[최종본]/img/5.jpg
  reservation-page[최종본]/img/6.jpg
  reservation-page[최종본]/img/7.jpg
  reservation-page[최종본]/img/8.jpg
  reservation-page[최종본]/img/9.jpg
  reservation-page[최종본]/img/Group.svg
  reservation-page[최종본]/img/Vector-1.svg
  reservation-page[최종본]/img/Vector.svg
  reservation-page[최종본]/img/autum.jpg
  reservation-page[최종본]/img/autum1.jpg
  reservation-page[최종본]/img/autum2.jpg
  reservation-page[최종본]/img/autum3.jpg
  reservation-page[최종본]/img/user.jpg
  reservation-page[최종본]/src/modal.js
Labels: HTML, JS, CSS

#38 [조지연] confirmation page 1차 수정
  confirmation-page/css/confirm.css
  confirmation-page/html/confirm.html
  confirmation-page/src/reservation-cancel.js
  confirmation-page/src/reservation-search.js
Labels: 기능 향상

#41 [김지균]상세페이지 채팅 포커스 & 키워드 gif 추가
  main-page/html/main-page.html
  reservation-page/html/section01.html
  reservation-page/src/img/40대_y.gif
  reservation-page/src/img/가격_y.gif
  reservation-page/src/img/가까워요_y.gif
  reservation-page/src/img/가족_y.gif
  reservation-page/src/img/뷰좋아요_y.gif
  reservation-page/src/img/쉬기좋아요_y.gif
  reservation-page/src/img/여유일정_y.gif
  reservation-page/src/img/재밋어요_y.gif
  reservation-page/src/img/전문가이드_y.gif
  reservation-page/src/modal.js
Labels: JS

#43 [김우주] "이벤트 슬라이드" 버그 수정
  main-page/html/main-page.html
  main-page/src/section03.js
Labels: 버그

#44 [조지연] 파일트리 수정에 따른 Main page 상대참조 수정
  main-page.html
  main-page/css/main-page.css
Labels: HTML, CSS

#45 [조지연] 파일트리 수정에 따른 Confirmation page 상대참조 수정
  confirmation-page.html
  confirmation-page/css/confirmation-page.css
Labels: HTML, CSS

#48 Update README.md
  README.md
Labels: 문서 관련

#46 [조지연] main page, conf page 버그 수정
  confirmation-page/src/reservation-cancel.js
  confirmation-page/src/reservation-search.js
  main-page/css/main-page.css
Labels: 버그

#54 [김지균] 상세페이지 모달 클로즈 화면 조정&불필요한 주석제거& 구조변경
  reservation-page.html
  reservation-page/css/section.css
  reservation-page/src/modal.js
Labels: 버그, HTML, JS, CSS

#55 [조지연] confimation page JS 파일 함수화
  confirmation-page/src/reservation-search.js
Labels: 기능 향상, JS

#58 [조지연] confimation page 피드백 반영
  confirmation-page.html
  confirmation-page/css/confirmation-page.css
  confirmation-page/src/conf-page-cancel.js
  confirmation-page/src/conf-page-search.js
Labels: 기능 향상

#59 [조지연] confimation page 네이밍 변경
  common/css/common.css
  common/images/ormlogo.png
  confirmation-page/css/confirmation.css
  confirmation-page/src/conf-cancel.js
  confirmation-page/src/conf-search.js
  confirmation.html
Labels: 개선

#66 [공동작업] index.html 수정
  common/.DS_Store
  index.html
  main-page.html
  main-page/css/index.css
  main-page/src/images/ormlogo.png
  main-page/src/index-animation.js
  main-page/src/index-event.js
  main-page/src/index-product.js
  main-page/src/main-page-event.js
  main-page/src/main-page.js
  reservation-page/src/img/40대_y.gif
  reservation-page/src/img/가격_y.gif
  reservation-page/src/img/가까워요_y.gif
  reservation-page/src/img/가족_y.gif
  reservation-page/src/img/뷰좋아요_y.gif
  reservation-page/src/img/쉬기좋아요_y.gif
  reservation-page/src/img/여유일정_y.gif
  reservation-page/src/img/재밋어요_y.gif
  reservation-page/src/img/전문가이드_y.gif
Labels: 개선

#67 [공동작업] reservation.html 수정
  reservation-page.html
  reservation-page/css/reservation.css
  reservation-page/src/chat.js
  reservation-page/src/form.js
  reservation-page/src/modal.js
  reservation-page/src/review.js
  reservation.html
Labels: 개선

#68 [조지연] 공통 작업사항 적용, 웹 표준 적용
  confirmation-page/css/confirmation.css
  confirmation-page/src/conf-cancel.js
  confirmation-page/src/conf-search.js
  confirmation.html
  index.html
  main-page/css/index.css
  reservation-page/css/reservation.css
  reservation.html
Labels: 개선

#69 [조지연] main 페이지 함수 개선
  main-page/src/index-event.js
  main-page/src/index-product.js
Labels: 개선
